services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
    container_name: ninive_front
    tty: true
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
