services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
    container_name: ninive_front
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
